In [20]:
##Garantir o endereços de toda estrutura GOLD
from pathlib import Path

BASE = Path("../data/gold")
for path in BASE.rglob("*.parquet"):
    print(path)

..\data\gold\facts\fato_alfabetizacao_brasil\fato_alfabetizacao_brasil.parquet
..\data\gold\facts\fato_alfabetizacao_municipio\fato_alfabetizacao_municipio.parquet
..\data\gold\facts\fato_alfabetizacao_uf\fato_alfabetizacao_uf.parquet
..\data\gold\dimensions\dim_municipio\dim_municipio.parquet
..\data\gold\dimensions\dim_rede\dim_rede.parquet
..\data\gold\dimensions\dim_tempo\dim_tempo.parquet
..\data\gold\dimensions\dim_uf\dim_uf.parquet

### Explorando as dimensões

In [26]:
import pandas as pd

df_municipio = pd.read_parquet("../data/gold/dimensions/dim_municipio/dim_municipio.parquet")

df_municipio.shape
#df_municipio.head(10)

(5549, 3)

In [27]:
df_municipio.head(10)

  id_municipio            Municipio  UF
0      5200050      Abadia de Goiás  GO
1      3100104  Abadia dos Dourados  MG
2      5200100            Abadiânia  GO
3      1500107           Abaetetuba  PA
4      3100203               Abaeté  MG
5      2300101              Abaiara  CE
6      2900207                Abaré  BA
7      4100103               Abatiá  PR
8      2900108               Abaíra  BA
9      4200051        Abdon Batista  SC

In [28]:
df_municipio.columns.tolist()

['id_municipio', 'Municipio', 'UF']

In [40]:
df_municipio.describe(include="all")

       id_municipio  Municipio    UF
count          5548       5548  5548
unique         5548       5279    27
top         5200050  Bom Jesus    MG
freq              1          5   853

In [32]:
df_municipio.isna().sum()

id_municipio    1
Municipio       1
UF              1
dtype: int64

In [33]:
df_municipio.duplicated().sum()

np.int64(0)

In [35]:
df_municipio["UF"].value_counts()

UF
MG    853
SP    642
RS    493
BA    417
PR    399
SC    295
GO    245
PI    224
PB    223
MA    217
PE    185
CE    184
RN    167
PA    144
MT    141
TO    139
AL    102
RJ     92
MS     79
ES     78
SE     75
AM     61
RO     53
AC     22
AP     16
DF      1
RR      1
Name: count, dtype: int64

Ao todo o Brasil possui 5.569 municípios, mas se imagina que nem todos possuem uma meta definida, justificando a divergência para os 5.548 municípios da base GOLD, mas resgatando os dados da camada BRONZE foi possível verificar que os dados são mantidos, não havendo nenhum ponto de atenção aqui.