In [ ]:
import sys
sys.path.append("..")

from src.analytical.build_base_analitica import build_base_analitica

In [ ]:
import pandas as pd

dim_municipio = pd.read_parquet(
    "../data/gold/dimensions/dim_municipio/dim_municipio.parquet"
)

df = pd.read_parquet(
    "../data/gold/facts/fato_alfabetizacao_municipio/fato_alfabetizacao_municipio.parquet"
)

In [ ]:
df_analitica = build_base_analitica(
    df,
    dim_municipio
)

In [4]:
df_analitica.shape

(4611, 11)

In [5]:
df_analitica["id_municipio"].nunique()

4611

In [6]:
df_analitica["UF"].nunique()

26

In [7]:
df_analitica["target_atingiu_meta_2024"].value_counts(normalize=True)

target_atingiu_meta_2024
0    0.618955
1    0.381045
Name: proportion, dtype: float64

In [8]:
df_analitica.isna().sum()

id_municipio                 0
taxa_alfabetizacao_2023      0
taxa_presenca_2023           0
taxa_preenchimento_2023      0
alunos_avaliados_2023        0
alunos_alfabetizados_2023    0
alunos_presentes_2023        0
provas_preenchidas_2023      0
meta_2024                    0
target_atingiu_meta_2024     0
UF                           0
dtype: int64

### Estatísticas da base analítica

In [9]:
print("===== SHAPE =====")
print(df_analitica.shape)

print("\n===== COLUNAS =====")
print(df_analitica.columns.tolist())

print("\n===== TIPOS =====")
print(df_analitica.dtypes)

print("\n===== NULOS =====")
print(df_analitica.isna().sum())

print("\n===== MUNICÍPIOS =====")
print(df_analitica["id_municipio"].nunique())

print("\n===== UFs =====")
print(df_analitica["UF"].nunique())

===== SHAPE =====
(4611, 11)

===== COLUNAS =====
['id_municipio', 'taxa_alfabetizacao_2023', 'taxa_presenca_2023', 'taxa_preenchimento_2023', 'alunos_avaliados_2023', 'alunos_alfabetizados_2023', 'alunos_presentes_2023', 'provas_preenchidas_2023', 'meta_2024', 'target_atingiu_meta_2024', 'UF']

===== TIPOS =====
id_municipio                     str
taxa_alfabetizacao_2023      float64
taxa_presenca_2023           float64
taxa_preenchimento_2023      float64
alunos_avaliados_2023          int64
alunos_alfabetizados_2023      int64
alunos_presentes_2023          int64
provas_preenchidas_2023        int64
meta_2024                    float64
target_atingiu_meta_2024       int64
UF                               str
dtype: object

===== NULOS =====
id_municipio                 0
taxa_alfabetizacao_2023      0
taxa_presenca_2023           0
taxa_preenchimento_2023      0
alunos_avaliados_2023        0
alunos_alfabetizados_2023    0
alunos_presentes_2023        0
provas_preenchidas_2023      0
meta_2024                    0
target_atingiu_meta_2024     0
UF                           0
dtype: int64

===== MUNICÍPIOS =====
4611

===== UFs =====
26

In [10]:
df_analitica["target_atingiu_meta_2024"].value_counts(
    normalize=True
).mul(100).round(2)

target_atingiu_meta_2024
0    61.9
1    38.1
Name: proportion, dtype: float64

In [11]:
df_analitica.groupby(
    "target_atingiu_meta_2024"
).agg(
    municipios=("id_municipio", "count"),
    alfabetizacao_2023=("taxa_alfabetizacao_2023", "mean"),
    presenca_2023=("taxa_presenca_2023", "mean"),
    preenchimento_2023=("taxa_preenchimento_2023", "mean"),
    alunos_avaliados=("alunos_avaliados_2023", "mean")
)

,municipios,alfabetizacao_2023,presenca_2023,preenchimento_2023,alunos_avaliados
target_atingiu_meta_2024,,,,,
0,2854,54.735680,88.399846,88.392239,416.787316
1,1757,55.116949,92.065862,92.057479,195.154809

Parece que os municípios que atingiram a meta em 2024 já tinham um indicador melhor de alfabetização em 2023, além de indíce maiores de presença e preenchimento. Hipótese de evasão escolar em municípios que não atingiram a meta.

In [13]:
df_analitica.groupby("UF").agg(
    municipios=("id_municipio", "count"),
    taxa_alfabetizacao_2023=(
        "taxa_alfabetizacao_2023",
        "mean"
    ),
    taxa_presenca_2023=(
        "taxa_presenca_2023",
        "mean"
    ),
    taxa_preenchimento_2023=(
        "taxa_preenchimento_2023",
        "mean"
    ),
    percentual_atingiu_meta=(
        "target_atingiu_meta_2024",
        "mean"
    )
).sort_values(
    "municipios",
    ascending=False
)

,municipios,taxa_alfabetizacao_2023,taxa_presenca_2023,taxa_preenchimento_2023,percentual_atingiu_meta
UF,,,,,
MG,801,58.480762,91.944906,91.944906,0.626717
RS,421,64.573919,87.552660,87.552660,0.057007
PR,395,68.192456,89.254177,89.254177,0.184810
BA,394,33.354721,86.792234,86.792234,0.124365
GO,242,65.208306,89.672934,89.672934,0.636364
SC,238,58.129958,84.900714,84.900714,0.151261
PI,224,57.728348,95.537009,95.537009,0.544643
PB,220,49.488727,90.749273,90.749273,0.450000
MA,216,56.146991,91.182500,91.182500,0.416667
CE,184,86.266739,96.235326,96.235326,0.880435
PE,184,56.511957,93.556033,93.556033,0.521739
MT,139,52.683381,88.933669,88.933669,0.417266
RN,139,31.866619,84.333165,84.333165,0.294964
TO,137,33.941679,87.377518,87.377518,0.416058
PA,136,38.855882,82.184706,82.184706,0.125000
AL,102,43.994020,94.827255,94.827255,0.480392
RJ,89,46.779663,83.312809,83.312809,0.056180
MS,79,46.578228,90.718987,90.257722,0.493671
ES,78,66.625256,90.872692,90.872692,0.397436
SE,75,29.592267,99.866667,99.866667,0.373333
RO,52,59.145192,89.405769,89.405769,0.269231
AM,47,39.252340,80.640426,80.640426,0.127660
AP,16,39.033750,90.837500,90.837500,0.312500
AC,1,38.490000,75.730000,75.730000,0.000000
RR,1,43.750000,86.780000,86.780000,0.000000
SP,1,55.880000,85.290000,85.290000,0.000000

Observa-se que na base atual existem estados, como o caso de SP, que estão sub-representados em volume de municípios. Todavia, sabemos que existe bases auxiliares que podem ser usados para enriquecer a base de dados.